language: node_js
node_js:
 - "0.10"
services: sqlite3
before_install:
 - npm install -g grunt-cli
 - npm install -g bower
 - npm install -g sqlite3
 - sudo apt-get autoremove sqlite3
 - sudo apt-add-repository -y ppa:travis-ci/sqlite3
 - sudo apt-get -y update
 - sudo apt-cache show sqlite3
 - sudo apt-get install sqlite3=3.7.15.1-1~travis1
 - sudo sqlite3 -version
install: npm install
