language: node_js
node_js:
 - "0.10"
 - "0.11"
 - "0.12"
before_install:
 - npm install -g grunt-cli
 - npm install -g bower
 - npm install sequelize
 - npm install sqlite3
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install: npm install
